#!/usr/bin/env python3
"""Builds the self-hosted Georgian fonts in static/fonts/ and their CSS in src/fonts.generated.css.

Downloads the BPG fonts from Debian's fonts-bpg-georgian source package, keeps only the
Georgian letters (plus space), rewrites the vertical metrics from the real glyph bounds so
every font lines up with the copybook staff, and writes WOFF2. Needs: pip install fonttools brotli
"""
import io
import urllib.parse
import urllib.request

from fontTools import subset
from fontTools.pens.boundsPen import BoundsPen
from fontTools.ttLib import TTFont

DEBIAN = 'https://sources.debian.org/data/main/f/fonts-bpg-georgian/2012-5/'
LETTERS = 'აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ'
TARGET_X = 0.536  # x-height of Noto Sans Georgian, so every style reads at the same size
PAD = 0.12  # em of air above and below the staff, as Noto Sans has
MAX_ASC = 0.86  # cap for tall calligraphic ascenders, so no style towers over the others

FONTS = {
    # key: (source file, CSS family)
    'serif': ('BPG_Serif_Modern_GPL&GNU.ttf', 'BPG Serif Modern'),
    'pen': ('BPG_Mikhail_Stephan_GPL&GNU.otf', 'BPG Mikhail Stephan'),
    'round': ('BPG_Glaho_GPL&GNU_2011.ttf', 'BPG Glaho'),
}


def bounds(font, char):
    glyphs = font.getGlyphSet()
    pen = BoundsPen(glyphs)
    glyphs[font.getBestCmap()[ord(char)]].draw(pen)
    return pen.bounds  # xMin, yMin, xMax, yMax


def build(key, src, family):
    raw = urllib.request.urlopen(DEBIAN + urllib.parse.quote(src)).read()
    font = TTFont(io.BytesIO(raw))
    upm = font['head'].unitsPerEm

    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.layout_features = ['*']
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=[0x20] + [ord(c) for c in LETTERS])
    sub.subset(font)

    all_bounds = [bounds(font, c) for c in LETTERS]
    top = max(b[3] for b in all_bounds)
    bottom = -min(b[1] for b in all_bounds)
    ascent, descent = round(top * 1.04), round(bottom * 1.04)  # a little air above and below
    hhea, os2 = font['hhea'], font['OS/2']
    hhea.ascent, hhea.descent, hhea.lineGap = ascent, -descent, 0
    os2.sTypoAscender, os2.sTypoDescender, os2.sTypoLineGap = ascent, -descent, 0
    os2.usWinAscent, os2.usWinDescent = ascent, descent
    os2.version = max(os2.version, 4)
    os2.fsSelection |= 1 << 7  # USE_TYPO_METRICS
    font.save(f'static/fonts/{key}.woff2')

    x = bounds(font, 'ა')[3] / upm
    asc = bounds(font, 'ბ')[3] / upm
    desc = -bounds(font, 'ქ')[1] / upm
    a, d = ascent / upm, descent / upm
    s = min(TARGET_X / x, MAX_ASC / asc)
    # Distances from the top of the staff box, in em of the element's font size.
    em = lambda v: f'{v * s + PAD:.3f}em'
    lh = (a + d) * s + 2 * PAD
    return (
        f"@font-face {{\n\tfont-family: '{family}';\n\tsrc: url('/fonts/{key}.woff2') format('woff2');\n"
        f"\tfont-display: swap;\n\tsize-adjust: {s * 100:.1f}%;\n}}\n"
        f":root[data-glyph='{key}'] {{\n\t--font-glyph: '{family}', var(--font-glyph-sans);\n\t--staff-lh: {lh:.3f};\n"
        f"\t--staff-asc: {em(a - asc)};\n\t--staff-x: {em(a - x)};\n\t--staff-base: {em(a)};\n\t--staff-desc: {em(a + desc)};\n}}\n"
    )


if __name__ == '__main__':
    css = ''.join(build(key, src, family) for key, (src, family) in FONTS.items())
    with open('src/fonts.generated.css', 'w') as out:
        out.write('/* Generated by scripts/build-fonts.py. Do not edit by hand. */\n' + css)
    print(css)
