#!/usr/bin/env python3
"""Counts how often each Mkhedruli letter appears in Georgian text.

Source: random articles from the Georgian Wikipedia, read through the public API. Writes
src/lib/frequency.generated.ts. Rerun it to refresh the numbers; the sample is large enough that
the ordering barely moves between runs.

    python3 scripts/letter-frequency.py [articles]
"""

import json
import sys
import urllib.parse
import urllib.request
from collections import Counter
from datetime import date

API = "https://ka.wikipedia.org/w/api.php"
LETTERS = "აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ"
BATCH = 20
UA = "anbani-letter-frequency/1.0 (https://github.com/tant/anbani)"


def fetch(params):
    url = f"{API}?{urllib.parse.urlencode({**params, 'format': 'json', 'formatversion': 2})}"
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=60) as r:
        return json.loads(r.read())


def sample(articles):
    counts = Counter()
    seen = 0
    while seen < articles:
        data = fetch(
            {
                "action": "query",
                "generator": "random",
                "grnnamespace": 0,
                "grnlimit": BATCH,
                "prop": "extracts",
                "explaintext": 1,
                "exlimit": BATCH,
            }
        )
        for page in data.get("query", {}).get("pages", []):
            counts.update(c for c in page.get("extract", "") if c in LETTERS)
            seen += 1
        print(f"  {seen}/{articles} bài, {sum(counts.values())} chữ cái", file=sys.stderr)
    return counts


def main():
    articles = int(sys.argv[1]) if len(sys.argv) > 1 else 400
    counts = sample(articles)
    total = sum(counts.values())
    if not total:
        raise SystemExit("no Georgian letters found")

    lines = [
        "// Generated by scripts/letter-frequency.py — do not edit by hand.",
        f"// Share of all Mkhedruli letters, in percent, over {total} letters",
        f"// from {articles} random Georgian Wikipedia articles, {date.today().isoformat()}.",
        "export const FREQUENCY: Record<string, number> = {",
    ]
    for letter in sorted(LETTERS, key=lambda c: -counts[c]):
        lines.append(f"\t'{letter}': {counts[letter] / total * 100:.2f},")
    lines.append("};\n")

    out = "src/lib/frequency.generated.ts"
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"{out} ready: {total} letters from {articles} articles")


if __name__ == "__main__":
    main()
